<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Comparison-Operators" data-toc-modified-id="Comparison-Operators-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Comparison Operators</a></span><ul class="toc-item"><li><span><a href="#Opearators-on-numbers" data-toc-modified-id="Opearators-on-numbers-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Opearators on numbers</a></span></li><li><span><a href="#Opearators-on-Strings" data-toc-modified-id="Opearators-on-Strings-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Opearators on Strings</a></span></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Exercises</a></span></li></ul></li><li><span><a href="#Boolean-Operators" data-toc-modified-id="Boolean-Operators-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Boolean Operators</a></span><ul class="toc-item"><li><span><a href="#boolean-operator-(and)" data-toc-modified-id="boolean-operator-(and)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>boolean operator (and)</a></span></li><li><span><a href="#Boolean-operator-(or)" data-toc-modified-id="Boolean-operator-(or)-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Boolean operator (or)</a></span></li><li><span><a href="#boolean-operator-(not)" data-toc-modified-id="boolean-operator-(not)-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>boolean operator (not)</a></span></li><li><span><a href="#Numpy-Array-(boolean-operators)" data-toc-modified-id="Numpy-Array-(boolean-operators)-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Numpy Array (boolean operators)</a></span></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Exercises</a></span></li></ul></li><li><span><a href="#Arithmetic-Operators" data-toc-modified-id="Arithmetic-Operators-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arithmetic Operators</a></span><ul class="toc-item"><li><span><a href="#If-else-syntax" data-toc-modified-id="If-else-syntax-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>If-else syntax</a></span></li><li><span><a href="#Extended-if-elif-else-syntax" data-toc-modified-id="Extended-if-elif-else-syntax-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Extended if-elif-else syntax</a></span></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Exercises</a></span></li></ul></li><li><span><a href="#Filtering-Pandas-DataFrame" data-toc-modified-id="Filtering-Pandas-DataFrame-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Filtering Pandas DataFrame</a></span><ul class="toc-item"><li><span><a href="#Exercises" data-toc-modified-id="Exercises-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Exercises</a></span></li></ul></li></ul></div>

- **Course: Intermediate Python**
    - Chap3: Logic, Control Flow and Filtering
    - Chap4: Loops

- **Course: Python Data Science Toolbox (Part 1)**
    - Chap1: Writing your own functions
    - Chap3: Lambda Functions and Error Handling
        
- **Course: Python Data Science Toolbox (Part 2)**
    - Chap2: List comprehensions and generators

## Comparison Operators
- Operators that can tell how two Python values relate of same types (exception: few cases, where different types relate. Float and Integers)
- In general, make sure to make comparison between objects of the same data types
- Returns boolean (True or False)
- Use operators works on numbers and strings
- True corresponds to 1, False corresponds to 0.

### Opearators on numbers

In [1]:
2 < 3

True

In [2]:
2 == 3

False

In [3]:
3 == 3

True

In [4]:
3 >= 2  

True

In [5]:
3 >= 3

True

### Opearators on Strings
- Ranked according to alphabets
- carl comes first before chris

In [8]:
'chris' > 'carl'

True

- 'b' is bigger than 'a'
- assume, a = 1, b = 2

In [9]:
'a' > 'b'

False

Different data types object cannot be compared
- numeric and strings

In [10]:
3 > 'a'

TypeError: '>' not supported between instances of 'int' and 'str'

Exception: numeric and float, although different data types, but can be compared

In [11]:
3 > 5.2

False

In [2]:
import numpy as np
np_weight = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_height = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_weight/np_height**2

In [3]:
bmi = np.array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [4]:
bmi > 23

array([False, False, False,  True, False])

In [5]:
bmi[bmi>23]

array([24.747])

![Comparison_Operators](comparison_operators.PNG)

### Exercises

In [6]:
# Comparison of booleans
print(True == False)

# Comparison of integers
print(-5 * 15 != 75)

# Compare a boolean with an integer
print(True == 1) 

False
True
True


Takes capitalization into account

In [7]:
# Comparison of strings
print('Pyscript' == 'PyScript')

False


In [8]:
# Comparison of strings
print('Pyscript' > 'PyScript')

True


In [9]:
# Comparison of integers
x = -3 * 6
print(x >= -10)

# Comparison of strings
y = "test"
print(y <= y)

# Comparison of booleans
print(True > False)

False
True
True


Using comparison operators, generate boolean arrays that answer the following questions:

Which areas in my_house are greater than or equal to 18?
You can also compare two Numpy arrays element-wise. Which areas in my_house are smaller than the ones in your_house?

In [10]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house >= 18)

# my_house less than your_house
print(my_house < your_house)

[ True  True False False]
[False  True  True False]


## Boolean Operators
- use boolean operators with comparison operators
- Three most common boolean operators are:
    - and: If all conditions are True, then True. Otherwise, False.
    - or: when at least one condition is True, then it is True. Otherwise, False
    - not

### boolean operator (and) 

In [33]:
True and True

True

In [34]:
True and False

False

In [36]:
False and True

False

In [35]:
False and False

False

- use boolean operators (and, or , not) with comparison operators (>,<, >=,<=, ==, !=)
- only one equal sign (=) means assigning value to a variable, it does not mean equal. The real equal is (==)
- a = 1 is a variable. a==b means actual equal 

In [37]:
x = 12
# True and True is True
x > 5 and x < 15

True

### Boolean operator (or)

In [38]:
True or True

True

In [39]:
False or True

True

In [40]:
True or False

True

In [41]:
False or False

False

In [42]:
y = 5
y < 7 or y > 13

True

### boolean operator (not) 

In [43]:
not True

False

In [44]:
not False

True

### Numpy Array (boolean operators)
- logical_and()
- logical_or()
- logical_not()

Which BMI is higher than 21 and lower than 22?

In [46]:
bmi

array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [50]:
import numpy as np
np.logical_and(bmi > 21, bmi < 22) 

array([ True, False,  True, False,  True])

In [51]:
bmi[np.logical_and(bmi>21, bmi <22)]

array([21.852, 21.75 , 21.441])

### Exercises

In [11]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen > 10 and my_kitchen < 18) 

# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen < 14 or my_kitchen > 17)

# Double my_kitchen smaller than triple your_kitchen?
print(my_kitchen * 2 < your_kitchen * 3)

False
True
True


In [53]:
x = 8 
y = 9
not(x < 3) and not(y > 14 or y > 10)

True

In [55]:
not(x<3)

True

In [56]:
not(y > 14 or y > 10)

True

In [58]:
not(x<3) and not(y > 14 or y > 10)

True

In [59]:
not(not(x<3) and not(y>14 or y>10))

False

In [60]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11,your_house <11))

[False  True False  True]
[False False False  True]


## Arithmetic Operators
- addition: +
- substraction: -
- division: /
- multiply: *
- to the power: **
- remainder after division: % (aka modulo)

### If-else syntax

- Known as conditional statements: if-elif-else
- if condition matches, then execute the expression
- if conditon does not match, the expression will not be executed
- Indent Python code with four spaces or one shift to tell python what to do if condition matches
- to exit the if statement, simply continue with some python code without indentation. It will know that that it is not a part of if statement

- for else statement, no condition needs to be specified 
- corresponding expression (else expression) gets run if the condition of the if statement is not true

In [ ]:
if condition:
    expression
else:
    expression

In [5]:
z = 4

if z % 2 == 0:
    print('it is even')
else: 
    print('it is odd')

it is even


In [7]:
z = 5
# Modulo operator 2 will return 0, if z is even
if z % 2 == 0:
    print('checking ' + str(z))
else:
    print('it is an odd number')

it is an odd number


Condition does not match/not true, hence, expression is not executed

The % symbol in Python is called the Modulo Operator. It returns the remainder of dividing the left hand operand by right hand operand. It's used to get the remainder of a division problem.



- (%) keeps dividing 4 by 2 and stops when it cannot be divided without using decimal, untill it gets a remainder value. In this case, the remainder value is zero. However, if the value 

In [72]:
4 % 2

0

In [73]:
6 % 3

0

In [74]:
7 % 2

1

### Extended if-elif-else syntax
- Note: if and elif can specify conditions and expression, but else cannot have any condition, but only expressin.
- when if and elif condition is not true, then else expression will be executed

In [ ]:
if condition:
    expression
elif condition:
    expression
else:
    expression

In [9]:
z = 4
if z % 2 ==0:
    print('z is divisible by 2')
elif z % 3 == 0:
    print('z is divisible by 3')
else:
    print('z is neither divisible by 2 nor by 3')

z is divisible by 2


What happens when both if and elif condition is true?
- As soon as Python bumps into a condition that is true, it executes the corresponding code and then leaves the control structure after that. This means the second condition, corresponding to the elfi, is never reached so there is no corresponding printout

In [10]:
z = 6
if z % 2 ==0:
    print('z is divisible by 2')
elif z % 3 == 0:
    print('z is divisible by 3')
else:
    print('z is neither divisible by 2 nor by 3')

z is divisible by 2


### Exercises

In [11]:
area = 10
if area < 9:
    print('small')
elif area < 12:
    print('medium')
else:
    print('large')

medium


In [12]:
# Define variables
room = "kit"
area = 14.0

# if statement for room
if room == "kit" :
    print("looking around in the kitchen.")

# if statement for area
if area > 15:
    print('big place!')

looking around in the kitchen.


In [15]:
# Define variables
room = "kit"
area = 14.0

# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print('pretty small.')

looking around in the kitchen.
pretty small.


In [17]:
# Define variables
room = "bedroom"
area = 14.0

# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print('pretty small.')

looking around elsewhere.
pretty small.


In [12]:
# Define variables
room = "bed"
area = 14.0

# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")

# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10:
    print('medium size, nice!')
else:
    print("pretty small.")

looking around in the bedroom.
medium size, nice!


## Filtering Pandas DataFrame

In [13]:
import pandas as pd 
brics = pd.read_csv('brics.csv', index_col=0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

* Select countries with area over 8 million km

First Way

In [14]:
brics[brics['area']>8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

Second Way

In [15]:
brics['area']>8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

* Countries with area between 8 and 10 km

* Since pandas is built on numpy, use numpy's boolean operators on pandas DataFrame

In [16]:
import numpy as np
brics[np.logical_and(brics['area']>8, brics['area']<10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

### Exercises

In [17]:
import pandas as pd 
cars = pd.read_csv('cars.csv', index_col=0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [18]:
cars['drives_right']

US      True
AUS    False
JAP    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool

* Note: when there are boolean data types and subset into car df. It filters and keep only True results

In [19]:
cars[cars['drives_right']]

cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [42]:
dr = cars['drives_right']
sel = cars[dr]
sel

cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

* find cars_per_cap of over 500

In [43]:


# Create car_maniac: observations that have a cars_per_cap over 500
cpc = cars['cars_per_cap']
many_cars = cpc>500
car_maniac = cars[many_cars]

# Print car_maniac
print(car_maniac)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False


In [49]:
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars[cars['cars_per_cap']> 500]

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [20]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500
medium = cars['cars_per_cap']
between = np.logical_and(cars['cars_per_cap'] > 100, cars['cars_per_cap'] < 500) 
medium = cars[between]

# Print medium
print(medium)

    cars_per_cap country  drives_right
RU           200  Russia          True
